name: goroutershell
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  hooks_riverpod: ^2.1.3
  flutter:
    sdk: flutter
  go_router: ^8.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  generate: true
